# -*- coding: utf-8 -*-
"""sample_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9of9w11NPmXK0QOlhkDyoLILaE911yt
"""

'''
Function name: helloworld()
This function prints 'hello world'
'''
def helloworld():
  print('hello world')

helloworld()